[project]
name = "entregable-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Santiago Lillo Macías", email = "santilillomacias@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "pathlib>=1.0.1",
    "scikit-learn>=1.6.1",
]

[project.scripts]
entregable-ml = "entregable_ml:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
