[project]
name = "entregable-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Santiago Lillo Macías", email = "santilillomacias@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
entregable-ml = "entregable_ml:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
